spring.application.name=chatapp

server.port=${PORT:8082}

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Timezone
spring.jackson.time-zone=Europe/Kyiv

# JVM timezone
user.timezone=Europe/Kyiv